### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by maple123xx** [haiphanNJIT/PrivateDeepLearning#1]
Hello, I saw your code: PrivateDeepLearning/AdLM/MNIST/AdLM.py, The third step, perturb input feature Xij, you did not write. Can you tell me what these lines of code are? I want to implement this code.Thank you very much!

**Comment by haiphanNJIT** [comment]
Hi there, Line 162: z += noise; is where the noise in injected into the input. In Cifar10, line 203 (cifar10_input.py) distorted_image = tf.random_crop(distorted_image + W_conv1Noise, [height, width, 3]) is where the noise is injected.

**Comment by maple123xx** [comment]
Thank you very much! I will try this.

**Comment by XRui-Y** [comment]
> 你好，我看到你的代码：PrivateDeepLearning/AdLM/MNIST/AdLM.py，第三步，扰动输入特征Xij，你没有写。你能告诉我这几行代码是什么吗？我想实现这个代码。非常感谢！

Hi, did you successfully run the AdLM code, I'm running into some errors and would like to ask for advice
