### ISSUE TITLE
Why would it be necessary to divide the noise by L？

### ISSUE THREAD

**Issue by xhmjm** [haiphanNJIT/PrivateDeepLearning#3]
PrivateDeepLearning/AdLM/MNIST/AdLM.py，line 80，W_conv1Noise[0][i][j] = np.random.laplace(0.0, Delta2/((_beta[i+2][j+2])*epsilon2), 1)/L;
Why would it be necessary to divide the noise by L？

**Comment by haiphanNJIT** [comment]
Each data sample will have the same amount of noise np.random.laplace(0.0, Delta2/((_beta[i+2][j+2])*epsilon2), 1)/L injected. Aggregating this noise L times for data samples will cancel out the L.

**Comment by XRui-Y** [comment]
> PrivateDeepLearning/AdLM/MNIST/AdLM.py，第80行，W_conv1Noise[0][i][j] = np.random.laplace(0.0, Delta2/((_beta[i+2][j+2])* epsilon2 ), 1)/L; 为什么需要将噪声除以L？

Hi, did you successfully run the AdLM code, I'm running into some errors and would like to ask for advice

**Comment by xhmjm** [comment]
> > PrivateDeepLearning/AdLM/MNIST/AdLM.py，第80行，W_conv1Noise[0][i][j] = np.random.laplace(0.0, Delta2/((_beta[i+2][j+2])* epsilon2 ), 1)/L; 为什么需要将噪声除以L？
> 
> Hi, did you successfully run the AdLM code, I'm running into some errors and would like to ask for advice

你环境配的是对的么，作者有readme文件呀

**Comment by XRui-Y** [comment]
> > > PrivateDeepLearning/AdLM/MNIST/AdLM.py，第80行，W_conv1Noise[0][i][j] = np.random.laplace(0.0, Delta2/((_beta[i+2][j+2])* epsilon2), 1)/L;为什么需要将噪声除以L？
> > 
> > 
> > 您好，您是否成功运行了 AdLM 代码，我遇到了一些错误，想寻求建议
> 
> 你的环境配的是对的，作者有readme文件呀

It's configured according to the file. That's right.
